name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download Emoji Kitchen Metadata 💾
        uses: xsalazar/actions/downloader@master
        with:
          url: "https://raw.githubusercontent.com/xsalazar/emoji-kitchen-backend/main/app/metadata.json"
          filename: "src/Components/metadata.json"

      - name: Setup Node 🏗
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install and Build 🔧
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: gh-pages
          folder: build
          CLEAN: true # Automatically remove deleted files from the deploy branch
